# Copyright © 2018 VMware, Inc. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
---
# These tasks assemble a set of subscriptions rules into a subscription
# definition for the group.
- name: Set subscription definition name, subscription set
  set_fact:
    subscription_def_name: >-
      ansible_{{ greengrass_group_subscriptions[greengrass_group_name]
      | hash('md5') }}
    subscriptions: "{{ greengrass_group_subscriptions[greengrass_group_name] }}"
    subscription_details: {}
  when:
    - greengrass_group_subscriptions is defined
    - greengrass_group_name in greengrass_group_subscriptions
    - subscription_def_name is not defined or
      subscription_def_name == ""

- name: List subscription definitions
  command: "{{ aws }} greengrass list-subscription-definitions"
  register: subscription_definitions
  when:
    - subscription_definition_id is undefined
    - subscription_def_name is defined and subscription_def_name != ""

- name: Obtain current subscription definition by name
  set_fact:
    subscription_latest: >-
      {{ subscription_definitions.stdout |from_json |json_query(names_query) }}
  vars:
    names_query: "Definitions[?Name == '{{ subscription_def_name }}'] | [0]"
  when:
    - subscription_definitions.changed

- name: Obtain current subscription definition attributes
  set_fact:
    subscription_definition_id: >-
      {{ subscription_latest | json_query("Id") }}
    subscription_definition_arn: >-
      {{ subscription_latest | json_query("Arn") }}
    subscription_definition_version_arn: >-
      {{ subscription_latest | json_query("LatestVersionArn") }}
  when: subscription_latest is defined

# If there's not a subscription definition, make one
- name: Create subscription definition
  command: >
    {{ aws }} greengrass create-subscription-definition
    --name {{ subscription_def_name | default(ansible_date_time.iso8601) }}
  register: create_subscription_definition
  when:
    - subscription_definition_id is undefined or not subscription_definition_id
    - subscription_def_name is defined and subscription_def_name != ""

- name: Extract subscription definition
  set_fact:
    subscription_definition_id: >-
      {{ create_subscription_definition.stdout | from_json |
      json_query("Id")}}
    subscription_definition_arn: >-
      {{ create_subscription_definition.stdout | from_json |
      json_query("Arn")}}
    subscription_definition_version_arn: >-
      {{ create_subscription_definition.stdout | from_json |
      json_query("LatestVersionArn")}}
  vars:
    subscription_definition_id_query: "Id"
  when: create_subscription_definition.changed

- name: debug subscription data
  debug: var=subscription_details

- name: Create a subscription definition version
  block:
    - tempfile:
        state: directory
        suffix: sub_def
      register: tmp_sub
    - name: Template out subscription config
      template:
        src: subscription_definition.json.j2
        dest: "{{ tmp_sub.path }}/subscription_definition.json"
    - name: Create subscription definition version
      command: >
        {{ aws }} greengrass create-subscription-definition-version
        --subscription-definition-id {{ subscription_definition_id }}
        --subscriptions file://{{ tmp_sub.path }}/subscription_definition.json
      register: create_subscription_definition_version
    - name: Extract subscription definition version
      set_fact:
        subscription_definition_version: >-
          {{ create_subscription_definition_version.stdout | from_json |
          json_query("Version") }}
        subscription_definition_version_arn: >-
          {{ create_subscription_definition_version.stdout | from_json |
          json_query("Arn") }}
      when: create_subscription_definition_version.changed
  when:
    - subscription_definition_id is defined
    - subscription_definition_version_arn is undefined or
      subscription_definition_version_arn == ""
    - subscription_def_name is defined and subscription_def_name != ""

- name: Clear subscription definition name for next pass
  set_fact:
    subscription_def_name: ""
